### ISSUE TITLE
"Invalid Requests" from Quill/IA Writer to Kirby

### ISSUE THREAD

**Issue by bsebesta** [sebastiangreger/kirby3-micropublisher#6]
So, I'm relatively new to PHP, but fluent enough to have a Kirby 3 site that I'm testing with this (wonderful) plugin. I used [Quill](https://quill.p3k.io/) and [IA Writer](https://ia.net/writer) to test how it works. The plugin ultimately works in converting the title and text to a file in Kirby, but it's failing to convert the slugs and tag, and sending odd errors within Quill and IA Writer as well.

# Kirby Config
Here's my Kirby config first, in case there's something obviously wrong. It's mostly taken from the example above, and with no post types configured.

```
    'sgkirby.micropublisher.jwtkey' => '##################,
    'sgkirby.micropublisher.default.template' => 'note',
    'sgkirby.micropublisher.default.parent' => 'notes',
    'sgkirby.micropublisher.default.status' => 'listed',
    'sgkirby.micropublisher.default.slug' => 'default-slug',
    'sgkirby.micropublisher.default.render' => [
        'name'		=> [ 'title', 'No title' ],
        'content'	=> [ 'text', '' ],
        'category'	=> [ 'tags', null ],
        'published'	=> [ 'date', strftime( '%F %T' ), 'datetime' ],
    ],
```

# Case 1: Quill to Kirby
I tested Quill with Micropub, and know it works. Here's [a picture of my entry via skill](https://user-images.githubusercontent.com/19319401/93642199-e639c380-f9ba-11ea-92a9-d90ac8c5888c.png), and here's the raw request returned by MicropubRocks from when I sent it.

```
POST https://micropub.rocks/client/Et7Ddf1nrzPUGhaO/micropub HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Content-Length: 230
Accept: application/json
Authorization: Bearer abxTTE1jD6bNhfVlZtYgfipb7zcidcsXK4NKGN6fEUcgeRRAY875uSKb3OayIYZ7yV0q6dmn7JrI0EMaKXHcydR4Ydje87aY352AcfOrS5utRfbP9FD0rIM7YxuiURLl
Host: micropub.rocks

h=entry&
access_token=abxTTE1jD6bNhfVlZtYgfipb7zcidcsXK4NKGN6fEUcgeRRAY875uSKb3OayIYZ7yV0q6dmn7JrI0EMaKXHcydR4Ydje87aY352AcfOrS5utRfbP9FD0rIM7YxuiURLl&
content=%23+Hello+World%0A%0AGoodbye+World&
category%5B%5D=test&
mp-slug=test-send`
```
 When I try to send this same thing to Kirby, however, I'm informed that "Something went wrong! Your Micropub endpoint indicated that something went wrong creating the post." The specific data that came back was this:
```
HTTP/1.1 500 Internal Server Error
Date: Fri, 18 Sep 2020 20:38:50 GMT
Server: Apache
Upgrade: h2,h2c
Connection: Upgrade, close
Vary: Accept-Encoding
Transfer-Encoding: chunked
Content-Type: application/json; charset=UTF-8

{"status":"error","exception":"Kirby\\Exception\\PermissionException","code":"error.page.changeStatus.permission","message":"The status for this page cannot be changed","details":[],"file":"kirby\/src\/Cms\/PageRules.php","line":129}
```

What's interesting, a file **was** created in Kirby. In `/content/1_notes/1600461530`, a note.txt file was created, as follows:

```
Title: No title

----

Text:

# Hello World

Goodbye World

----

Tags: 
```

So it worked, but didn't work.

# Case 2: IA Writer to Kirby

I also tried putting [a similar file](https://user-images.githubusercontent.com/19319401/93643939-36665500-f9be-11ea-8098-5d740128cdc5.png) into both Micropub Rocks and Kirby via [IA Writer](https://ia.net/writer).

<img width="297" alt="CleanShot 2020-09-18 at 14 49 48@2x" src="https://user-images.githubusercontent.com/19319401/93643939-36665500-f9be-11ea-8098-5d740128cdc5.png">

I tried publishing to Micropub. I received [this error message](https://user-images.githubusercontent.com/19319401/93644013-631a6c80-f9be-11ea-96b7-dc6fd092f552.png), making it seem like something had gone wrong.

<img width="441" alt="CleanShot 2020-09-18 at 14 49 18@2x" src="https://user-images.githubusercontent.com/19319401/93644013-631a6c80-f9be-11ea-96b7-dc6fd092f552.png">

And indeed, Micropub immediately informed me that IA Writer is doing something wonky. "The request was not a form-encoded request. Ensure you are sending a proper form-encoded request with valid parameters." The raw request reads as follows:

```
POST https://micropub.rocks/client/V8ZkRvdK2v7erCW8/micropub HTTP/2.0
Authorization: Bearer eFAJ0xOUisikkhGb2P8Gl0SYG769phew1Yy47umoOWiVK4GPFS1Gqt3ajUhs7plDkla9LlgtgYXI8Nq69ZwyHzoRKscXvrFZiFflzKCqMEfUUExLrxUy7bMiQUwgYD9y
Accept-Language: en-us
User-Agent: iA%20Writer/56102 CFNetwork/1128.0.1 Darwin/19.6.0 (x86_64)
Accept-Encoding: gzip, deflate, br
Content-Length: 201
Accept-Charset: utf-8
Content-Type: application/json
Accept: application/json
Host: micropub.rocks

{"type":["h-entry"],"properties":{"name":["Hello World"],"content":[{"html":"<h1>Hello World<\/h1>\n\n<p>Goodbye World<\/p>\n\n<p><span class=\"hashtag\">#test<\/span><\/p>"}],"post-status":["draft"]}}
```

Undeterred, I tried to publish to Kirby. And though I received the same "Your request was invalid" error message in IA Writer, it seemed to (partially) work in Kirby. A file was created with the slug `1_notes/1600462155`. The `note.txt file rendered as follows:

```
Title: Hello World

----

Text:

# Hello World

Goodbye World

<span class="hashtag">#test</span>

----

Tags: 
```

# Questions
A few issues here, with the caveat that I'm relatively new to this, so please be kind if I've made some rookie mistakes or overlooked things.

1. Quill worked great with Micropub Rocks, but gave an error with Kirby. Yet, it also kind of worked–minus the slugs and tags (both of which were specified). What happened?
2. IA Writer gave an error with Micropub Rocks, and with Kirby, yet it too (kind of) worked–again, minus the slug (which should have been the default, I think?) and the tags (which were not specified). 
3. Why does the slug not convert properly from either Quill or IA Writer? With Quill, I _think_ it should have been `1_notes/test-send` (since that's what I put into the Quill). Instead, it came out as`1_notes/1600461530`.
4. Why do the tags not convert properly from Quill? It was specified in the Quill bank, but didn't make it over in either instance. I have a vague suspicion I don't have the config.php set up properly here, and perhaps should change the `[ 'tags', null ],` to something like `[ 'tags', 'category' ]`?

Also, I should add that while  I didn't expect the tags to convert from IA Writer, it would be cool if there was a way to recognize the hashtags within the text itself and shift them from the text block to the tags block. Some kind of setting that says, "expect hashtags in the block and convert/move them appropriately."

**Comment by sebastiangreger** [comment]
Hi! Thank you for the verbose documentation of the problems; this allows to go straight to their root :slightly_smiling_face:  We are looking at a few separate issues here.

## Missing slug

I believe that the slug problem should go away once you replace

`'sgkirby.micropublisher.default.slug' => 'default-slug',`

with 

`'sgkirby.micropublisher.default.slug' => 'slug',`

[This setting](https://github.com/sebastiangreger/kirby3-micropublisher#9-slug-design-rules-optional) is admittedly rather abstract, but the idea is that `'slug'` tells the endpoint to use a submitted mp-slug property as the post's slug. `'default-slug'` is not a valid value for this config field.

## Missing tags

Your config is correct on this part. But do you have the field `tags` set up in your `note` blueprint? If not, I believe that Kirby would not be able to store any data in it. I.e. you'd have to set up the `tags` field in the blueprint first, then this should work.

## The Quill error

Quill is brilliant for testing micropub endpoints thanks to its output of the returned error. The error you quoted, `"The status for this page cannot be changed"` indicates that something goes wrong as the newly created post is updated to `listed` as you configured in your config.

Please try the following:
1. Does this error go away once the slug issue (above) is fixed? This invalid config setting might throw off the process further down the line. This would be great news.
2. Please make sure that the `note` blueprint does not have an [option](https://getkirby.com/docs/reference/panel/blueprints/page#options) of `changeStatus: false` set. A wild shot, I know, but good to rule it out anyways.
3. If it still doesn't work: could you try and see if this problem persists if you change `'sgkirby.micropublisher.default.status' => 'listed',` to `'draft'`? If not, then I at least know where it goes awry and can investigate from there.

...I have a hunch that the issues with iA Writer are tied to the Quill problems, so we'll get back to those (if needed) once the Quill workflow is up and running. Quill is so much easier to debug with :wink:

**Comment by bsebesta** [comment]
Sebastian, thanks so much.

## Slug
I realize now that I misinterpreted what `'sgkirby.micropublisher.default.slug' => 'slug',` was doing; I thought it was a string (hence, my experiment with "default-slug") rather than an array with ranked rules. It works now, and I've learned my lesson: read the entire documentation. ;P Thanks for being patient there!

## Listed / Draft Status
Fixing the slug didn't fix the Quill problems, but the status did! Once I changed `'sgkirby.micropublisher.default.status' => 'listed',` to `'sgkirby.micropublisher.default.status' => 'draft',` everything went smoothly for both Quill and IA Writer.

Now, when I press publish, they take me straight to the draft page in Kirby. But when I have `'sgkirby.micropublisher.default.status' => 'listed',`, or when I have no value at all, I get the "Something went wrong" from Quill and the "Invalid Error" from IA Writer. Quill responded with what I think is the same message as above:

```
HTTP/1.1 500 Internal Server Error
Date: Sun, 20 Sep 2020 02:42:32 GMT
Server: Apache
Upgrade: h2,h2c
Connection: Upgrade, close
Vary: Accept-Encoding
Transfer-Encoding: chunked
Content-Type: application/json; charset=UTF-8

{"status":"error","exception":"Kirby\\Exception\\PermissionException","code":"error.page.changeStatus.permission","message":"The status for this page cannot be changed","details":[],"file":"kirby\/src\/Cms\/PageRules.php","line":129}
```

So I'll leave it in drafts for now–I have a few extra fields I have in my blueprint anyway. But if you have any idea what's happening here, LMK. I'm happy to try other things for the sake of improving the plugin, since this seems to be an issue keeping it from working out-of-the-box.

## Tags
Finally, tags. They are still not going through from Quill. You suggested I check the blueprint, and I did. Tags are specified.
```
  sidebar:
    width: 1/3
    sections:
      meta:
        type: fields
        fields:
          ...
          tags:
            label: "Ideas"
            type: tags
```

So it _should_ work. My `config.php` file still has the setting `'category'	=> [ 'tags', null ],` in place. Again, LMK if you'd like me to try something different or have any ideas here.

**Comment by sebastiangreger** [comment]
Thank you, Bryan, for reporting back and assisting in hunting down the potential roots of these issues!

Great to hear the slug is now working - no worries, I know very well how complex this plugin's setup is (due to the desire to make it as universal as possible, rather than plug-and-play). I will make it more explicit that this is an array, not a string, in the documentation for others' benefit.

## Tags

Regarding the missing tags it seems you indeed found a yet undiscovered bug. While it works with my personal site, I was able to reproduce the error on a vanilla Starterkit install. With the help of a few Indiewebbers on IRC (including Aaron, the author of Quill), the culprit has been identified and removed.

I created a `test` branch that contains a temporary version of the plugin - if you have a minute to test it, that would be highly appreciated! It can be found at https://github.com/sebastiangreger/kirby3-micropublisher/tree/test and the only relevant file that has changed is `classes/Micropublisher.php`.

You will have to log out of Quill and back in again in order for the changes to take effect (this was about the "capabilities" the plugin reports to Quill, and these are only checked on login). Once you log out and back in again the tags should start working - at least they did in my test environment.

## "Listed" status

This one is very tricky for me to track down, as I cannot reproduce the error. When testing this myself, setting the default status to "listed" works just fine on two separate websites. Yet, the error message gives me a clear indication where the processing goes wrong and above `test` branch includes a small attempt to maybe address a potential issue. If this doesn't help, I'll yet have to dig deeper.

**Comment by bsebesta** [comment]
Sebastian, excellent. That did the trick for the tags. They work like a charm. Many thanks to you and your fellow Indiewebbers.

The "listed" error persists, though. I still get this:

```
HTTP/1.1 500 Internal Server Error
Date: Sun, 20 Sep 2020 16:53:21 GMT
Server: Apache
Upgrade: h2,h2c
Connection: Upgrade, close
Vary: Accept-Encoding
Transfer-Encoding: chunked
Content-Type: application/json; charset=UTF-8

{"status":"error","exception":"Kirby\\Exception\\PermissionException","code":"error.page.changeStatus.permission","message":"The status for this page cannot be changed","details":[],"file":"kirby\/src\/Cms\/PageRules.php","line":129}
```

Again, what's strange is that it actually *does* make a listed page within the `1_notes` folder, albeit without the date part of the slug (probably because I haven't specified the proper slug prefix). See below, where "test," "test-three," and "three-cheese-enchilada" were all made through Quill with the draft set by default to publish/listed. (If I changed the setting to drafts, it works fine.)

<img width="261" alt="CleanShot 2020-09-20 at 10 56 15@2x" src="https://user-images.githubusercontent.com/19319401/93716968-f0310300-fb2f-11ea-886f-19c326fde660.png">

So it makes the file, but without the date prefix and throws me an error.

LMK what you think. Happy to try something else. I'm also happy to see if I do a fresh Kirby install on my server, if I can reproduce it; I can get back to you about that in a couple of days.

**Comment by sebastiangreger** [comment]
Brilliant -- two down, one to go :partying_face:

Your screenshot of the `1_notes` folder gives me one more idea. It looks like the post is created as `unlisted` to start with and then the status change to `listed` is where it fails (the missing "date part" is how Kirby differentiates between "listed" posts -- those with a date or number prefix -- and "unlisted" posts -- those with no prefix).

I tried one more tiny change in an additional commit [in the `test` branch](https://github.com/sebastiangreger/kirby3-micropublisher/tree/test) -- again just the `classes/Micropublisher.php` file. I'd be somewhat surprised if this really fixes it, but go for it if you want to give it a try! (I'm removing one optional attribute as the content file is created ...I frankly never quite understood what is its function anyways -- so maybe that is our troublemaker)

Otherwise we indeed would have to rule out that this _"The status for this page cannot be changed"_ error is caused by collisions with anything else in your setup (which seems increasingly likely, as the plugin indeed works fine with "listed" visibility on my systems). I'm positive it's not about file rights on the server level, as Kirby obviously is happily writing to your disk. But there might be an interference from some plugin or config setting, and a fresh install would help eliminate that.

Myself, on the other hand, would then have to dive deeper into the processes involved in the CMS, maybe by reaching out to the Kirby community.
